spring:
  datasource:
    url: jdbc:h2:mem:jpa_practice
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret: "adapterz-spring-security-jwt-secret-key-for-practice-123456789"
  access-token-expiration-millis: 3600000